### ISSUE TITLE
fillScreen issue after setRotation

### ISSUE THREAD

**Issue by JiriBilek** [Bodmer/TFT_ILI9163#1]
Hi,
the sequence

```
  tft.init();
  tft.setRotation(1);
  tft.fillScreen(TFT_BLACK); 
```
leads to incomplete background setting. I suspect that after setRotation(1) the width and height dimensions of the screen are swapped and the fillScreen procedure gets confused.

**Comment by Bodmer** [comment]
I thought I tested that...

Are you sure you have a TFT with a ILI9163? Some other TFT drivers "almost" work with the library so it is worth checking with the screen vendor.

I will investigate further, in the meantime have you found a work-around for this until I can perform some tests, or does it make the library un-usable for your project?

**Comment by JiriBilek** [comment]
Bodmer, you are right, according to your testing sketch I have ST7735 chip :
```

TFT driver register values:
===========================
Register 0x01: 0x00
Register 0x04: 0x5C89F0
Register 0x09: 0x610000
Register 0x0A: 0x08
Register 0x0B: 0x00
Register 0x0C: 0x06
Register 0x0D: 0x00
Register 0x0E: 0x00
Register 0x0F: 0x00
Register 0x2E: 0xFFFFFF
Register 0xDA: 0x5C
Register 0xDB: 0x89
Register 0xDC: 0xF0
===========================

Looks like driver chip is: ST7735 (based on datasheet ID)

```
While testing I came to another strange behaviour - I will write it to the correct github project.
Closing the issue.

Thanks a lot and sorry for wasting your time.
