### ISSUE TITLE
Version of parallel interface

### ISSUE THREAD

**Issue by konkrog** [Bodmer/TFT_ILI9163#2]
Hi Bodmer,

this is not really an issue with the current library, as it is working fine... However, I have been spending some time looking for a TFT library for ILI9163 that supports parallel interface.

I've purchased http://www.newhavendisplay.com/nhd18128160efcsxnf-p-9493.html and it supports 8bit parallel only. I chose it because it is sunlight readable.

I have not found any version that supports parallel... so I'm now considering implementing that myself based on this library, but would very much appreciate some pointers on what parts needs rewriting.

Do you have any suggestions on how to best approach this?

Appreciate any input.

Thanks,
Knut

**Comment by Bodmer** [comment]
Ah, I see you have already made the changes in your next post!
