### ISSUE TITLE
1284P Bobuino pin out support

### ISSUE THREAD

**Issue by jarsoftelectrical** [Bodmer/TFT_ILI9163#4]
Hi
Is there any chance you can add support for the 1284P Bobuino pin outs within the FAST PIN code 

If not any pointers would be most appreciated.

Regards
Jason

**Comment by Bodmer** [comment]
It is [already supported](https://github.com/Bodmer/TFT_ILI9163/blob/master/TFT_FastPin.h#L350) as far as I can tell but I have not tested it.

The FAST PIN code has been inherited from another library.

**Comment by jarsoftelectrical** [comment]
Thank you for closing this issue ?
Your file has only support for the standard Pinout of the 1284P as you indicated.
I have updated my downloaded copy to work with the 1284P Bobuino version of the Pinout
